### ISSUE TITLE
ipfs pin queue log nil panic 

### ISSUE THREAD

**Issue by postables** [RTradeLtd/Temporal#158]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x99fc76]

goroutine 1 [running]:
github.com/RTradeLtd/Temporal/vendor/github.com/sirupsen/logrus.(*Logger).newEntry(0x0, 0x10)
        /home/solidity/go/src/github.com/RTradeLtd/Temporal/vendor/github.com/sirupsen/logrus/logger.go:79 +0x26
github.com/RTradeLtd/Temporal/vendor/github.com/sirupsen/logrus.(*Logger).WithFields(0x0, 0xc420195a30, 0x0)
        /home/solidity/go/src/github.com/RTradeLtd/Temporal/vendor/github.com/sirupsen/logrus/logger.go:102 +0x38
github.com/RTradeLtd/Temporal/queue.(*QueueManager).ProccessIPFSPins(0xc4201f4e10, 0xc4200b83c0, 0xc4204c6090, 0xc4200ea480, 0xf, 0x0)
        /home/solidity/go/src/github.com/RTradeLtd/Temporal/queue/ipfs.go:140 +0x512
github.com/RTradeLtd/Temporal/queue.(*QueueManager).ConsumeMessage(0xc42035c030, 0x0, 0x0, 0xc42023c0e0, 0x1f, 0xc4204d8210, 0xd, 0xc42019a000, 0x73, 0xc4204d84a0, ...)
        /home/solidity/go/src/github.com/RTradeLtd/Temporal/queue/queue.go:280 +0x860
main.main()
        /home/solidity/go/src/github.com/RTradeLtd/Temporal/main.go:84 +0xbcd

**Comment by postables** [comment]
see latest commit for a fix
